server:
  port: 7070

#
#logging:
#  file:
#    name: api_gateway.log  
  
spring:

  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
       
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
        
        
        
        
      - id: POLICY-SERVICE
        uri: lb://POLICY-SERVICE
        predicates:
        - Path=/policy/**
       
       
        
      - id: PAYMENT-SERVICE
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment/**
       
        

      - id: DOCUMENT-SERVICE
        uri: lb://DOCUMENT-SERVICE
        predicates:
        - Path=/document/**
        
       
       
      - id: CLAIM-SERVICE
        uri: lb://CLAIM-SERVICE
        predicates:
        - Path=/calim/**
      
        

      - id: NOTIFICATION-SERVICE
        uri: lb://NOTIFICATION-SERVICE
        predicates:
        - Path=/notification/**
     
  main:
    web-application-type: reactive
        

