server:
  port: 5555

#
#logging:
#  file:
#    name: api_gateway.log  
  
spring:

#  config:
#    import: optional:configserver:http://localhost:8888

  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
    
      globalcors:
        add-to-simple-url-handler-mapping: true

        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
    
    
    
    
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
        
#        filters:
#        - AuthenticationFilter
#        
#        
#      - id: DC-SERVICE
#        uri: lb://DC-SERVICE
#        predicates:
#        - Path=/DC/**
#        filters:
#        - AuthenticationFilter
#       
#        
#      - id: ED-SERVICE
#        uri: lb://ED-SERVICE
#        predicates:
#        - Path=/ED/**
#        filters:
#        - AuthenticationFilter
#        
#
#      - id: CO-SERVICE
#        uri: lb://CO-SERVICE
#        predicates:
#        - Path=/CO/**
#        filters:
#        - AuthenticationFilter
#       
#       
#       
#      - id: PLAN-SERVICE
#        uri: lb://PLAN-SERVICE
#        predicates:
#        - Path=/PlanMaster/**
#        filters:
#        - AuthenticationFilter
#        
#
#      - id: REPORT-SERVICE
#        uri: lb://REPORT-SERVICE
#        predicates:
#        - Path=/report/**
#        filters:
#        - AuthenticationFilter
#
#            
#      - id: BI-SERVICE
#        uri: lb://BI-SERVICE
#        predicates:
#        - Path=/BI/**
#        filters:
#        - AuthenticationFilter
#          
# 
#      - id: AUTH-SERVICE
#        uri: lb://AUTH-SERVICE
#        predicates:
#        - Path=/auth/**
        
  main:
    web-application-type: reactive